# Generated by Django 4.0.3 on 2022-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(),
        ),
    ]
